# Generated by Django 4.2.4 on 2023-08-11 07:48

from django.db import migrations, models
import planeyarium.models


class Migration(migrations.Migration):
    dependencies = [
        ("planeyarium", "0003_alter_astronomyshow_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="image",
            field=models.ImageField(
                null=True, upload_to=planeyarium.models.movie_image_file_path
            ),
        ),
    ]
